<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<process name="throw3-2.0"
  targetNamespace="http://ode/bpel/unit-test"
  xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/"
  xmlns="http://schemas.xmlsoap.org/ws/2004/03/business-process/"
  xmlns:tns="http://ode/bpel/unit-test"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:test="http://ode/bpel/unit-test.wsdl"
  suppressJoinFailure="yes">

  <import importType="http://schemas.xmlsoap.org/wsdl/"
    location="test.wsdl"
    namespace="http://ode/bpel/unit-test.wsdl" />

  <partnerLinks>
    <partnerLink name="testPartnerLink"
      partnerLinkType="test:TestPartnerLinkType"
      myRole="me" />
  </partnerLinks>

  <variables>
    <variable name="var1" messageType="test:TestMessage1"/>
  </variables>

  <sequence>
    <receive name="startReceive"
      createInstance="yes"
      partnerLink="testPartnerLink"
      portType="test:TestPortType"
      operation="testOperation"
      variable="var1"/>
    <scope>
      <faultHandlers>
        <catch faultName="test:testFault1"
          faultVariable="faultVar"
          faultMessageType="test:TestMessage1">
          <!-- we do NOT want to be here -->
          <assign>
            <copy>
              <from>'failure - wrong catch happened'</from>
              <to>$var1/TestPart</to>
            </copy>
          </assign>
        </catch>
        <catch faultName="test:testFault2"
          faultVariable="faultVar"
          faultMessageType="test:TestMessage1">
          <!-- we want to be here -->
          <assign>
            <copy>
              <from>'success'</from>
              <to>$var1/TestPart</to>
            </copy>
          </assign>
        </catch>
        <catchAll>
          <!-- we do NOT want to be here -->
          <assign>
            <copy>
              <from>'failure - catchAll happened'</from>
              <to>$var1/TestPart</to>
            </copy>
          </assign>
        </catchAll>
      </faultHandlers>
      <throw faultName="test:testFault2" faultVariable="var1"/>
    </scope>
    <reply name="endReply"
      operation="testOperation"
      partnerLink="testPartnerLink"
      portType="test:TestPortType"
      variable="var1"/>
  </sequence>

</process>
